### PR TITLE
build: update to latest aspect_bazel_lib, aspect_rules_js, aspect_rules_jasmine and aspect_rules_esbuild

### PR DESCRIPTION
**Pull request by gregmagolan**
There is a regression with worker mode in this release of rules_ts for Node 14 (works fine with Node 16) I disabled it in the ts_project targets in the PR. Sahin is working on a fix for Node 14 worker mode but the ts_project targets in the repository are small so worker mode doesn't add much anyway.

The latest version of rules_js will keep your pnpm-lock.yaml files up-to-date automatically (when your source-of-truth is a yarn.lock file) when any of the inputs to the npm_translate_lock repository rule change. The `.aspect/rules/external_repository_action_cache/npm_translate_lock_*` files act like an action cache to know when to re-run `pnpm import` to update the pnpm lock files.

UPDATE: Node 14 worker mode issue is now fixed in rules_ts 1.3.2 (with rules_js 1.20.3 transitive dep)

### CODE REVIEW

**Review by atscott — APPROVED** [review]

**Comment by devversion** [comment]
@gregmagolan is there a link for the regression so we can know when to remove the worker disabling?

**Comment by gregmagolan** [comment]
> @gregmagolan is there a link for the regression so we can know when to remove the worker disabling?

Fix is underway: https://github.com/aspect-build/rules_js/pull/927

**Review by devversion — APPROVED** [review]

**Comment by gregmagolan** [comment]
ts_project worker mode re-enabled with the latest rules_js & rules_ts releases cut this morning. I also greened up the other CI failure. This should be clear to land now

**Comment by devversion** [comment]
@gregmagolan I have a conflict-resolved version of your PR, along with the environment variable: https://github.com/angular/vscode-ng-language-service/pull/1873

**Pull request closed without merging**
