### PR TITLE
refactor: move syntax grammars to TS definitions

### PR DESCRIPTION
**Pull request by ayazhafiz**
This commit refactors remaining existing grammars to use TS definitions
as started in #581.

### CODE REVIEW

**Comment by ayazhafiz** [comment]
@dannymcgee if you'd like to take a look

**Comment by ayazhafiz** [comment]
That sounds good. Do you mind if I put that in the next PR? It goes well with putting the generated files in the root syntaxes directory, which makes development easier as well.

**Comment by kyliau** [comment]
Yeah separate PR is fine, thank you!

**Comment by dannymcgee** [comment]
> @dannymcgee if you'd like to take a look

Sorry I'm just seeing this, but looks good to me! The only thing I would note for the next PR is that if we're going to use PascalCase for the grammar identifiers we should probably also rename `template` to `Template`.

**Pull request merged**
