### PR TITLE
feat: provide snippets for attribute and method completions

### PR DESCRIPTION
**Pull request by ivanwonder**
when the user selects the attribute in the completion list, the position of the cursor is not expected. It should be in the middle of quotes.

### CODE REVIEW

**Comment by ayazhafiz** [comment]
re #521

**Comment by ivanwonder** [comment]
Yes, I think it's possible to move the code to the upstream package. Because this PR only does is rewrite the `insertText` and `replacementSpan`. But I just meet a problem here, for example `(clic|)`,  there will be no provided info for the user in vscode when the `replacementSpan` starts from `(`. https://github.com/angular/vscode-ng-language-service/blob/1ff56baad7ffe971e3ebbef500ed6642a3d84cff/server/src/completion.ts#L108
Maybe I need to look into it.

**Comment by kyliau** [comment]
> Thanks for the fix, this has been requested for some time. However, I think it would be better to provide this in the language service package so that other Angular language servers, like CoC can take advantage of it too. It is easier to test in the upstream package as well. WDYT?

More to your point this feature relies on snippet, which is available in the LSP protocol but not available in the Typescript interface. I think it's a good feature to have, but we should discuss if we want to have such complex logic in the extension layer.

I've briefly read about "Actions", but do not understand enough to know how they are used. Perhaps we could explore it a little more and see if it could be used here.

https://github.com/microsoft/TypeScript/blob/6c11ceb8db0a085144ee0041793b1e7faa4c172f/lib/tsserverlibrary.d.ts#L5752-L5768

**Comment by ayazhafiz** [comment]
My two cents: I don't think @angular/language-service needs to in total alignment with the tsserver API. We aren't currently. In my opinion the language service package should provide the best features it can, and then it should be the responsibility of the extension implementations to convert the features provided by the language service into types expected by the LSP implementation the extension is targeting. Of course the two pieces shouldn't diverge very far, but keeping the features of the core language service in one component makes it easier to develop new features without having to wait for users to catch up.

**Comment by ivanwonder** [comment]
I think it's better to let the `@angular/language-service` know the [client's capability](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_completion).


> Yes, I think it's possible to move the code to the upstream package. Because this PR only does is rewrite the `insertText` and `replacementSpan`. But I just meet a problem here, for example `(clic|)`, there will be no provided info for the user in vscode when the `replacementSpan` starts from `(`.
> 
> https://github.com/angular/vscode-ng-language-service/blob/1ff56baad7ffe971e3ebbef500ed6642a3d84cff/server/src/completion.ts#L108
> 
> 
> Maybe I need to look into it.

I found that the vscode will filter the completion items by the text cut by `textEdit`.
image
If we provide it in LS, Maybe we should return the completion item label with the symbol, for example `(click)`

**Comment by ivanwonder** [comment]
I find the issue about [snippet for TSServer](https://github.com/microsoft/TypeScript/issues/25207)

**Comment by atscott** [comment]
Closing, since we're implementing this in the @angular/language-service and then adding an option for handling it in the @angular/language-server

**Pull request closed without merging**
