### PR TITLE
feat: add config to enable auto-apply optional chaining on nullable symbol

### PR DESCRIPTION
**Pull request by ivanwonder**
wait for [PR](https://github.com/angular/angular/pull/42995) to land

### CODE REVIEW

**Comment by ivanwonder** [comment]
wait for [PR](https://github.com/angular/angular/pull/42995) to land

**Review by atscott — CHANGES_REQUESTED** [review]
We should also add a test for this. You'll have to make some updates:

* Update the `package.json` and `server/package.json` versions to be `13.0.0-next.2`. This is the version your change to `@angular/language-service` is in
* Update the test application's `tsconfig.json` to have `"strict": true` (this took me a while to figure out
* Add a test to `ivy_spec.ts`

Here's the commit where I finally got this to work: https://github.com/angular/vscode-ng-language-service/commit/7ed5d3f9f75e05c0269506db42223291a89fb690. You'll probably want to clean that up a bit more.

**Comment by ivanwonder** [comment]
> * Update the test application's `tsconfig.json` to have `"strict": true` (this took me a while to figure out

https://github.com/angular/vscode-ng-language-service/blob/ad5add9a8a4242664662aa150ca80a07ded1877f/package.json#L106

`Requires TS 3.7+ and strict null checks to be enabled`. It already adds to the description. I copy this from the extensions of ts in `vscode`

**Comment by atscott** [comment]
> > * Update the test application's `tsconfig.json` to have `"strict": true` (this took me a while to figure out
> 
> https://github.com/angular/vscode-ng-language-service/blob/ad5add9a8a4242664662aa150ca80a07ded1877f/package.json#L106
> 
> `Requires TS 3.7+ and strict null checks to be enabled`. It already adds to the description. I copy this from the extensions of ts in `vscode`

Yea, I just didn’t expect it to not already be enabled in the test project 😅

**Review by atscott — APPROVED** [review]

**Pull request merged**
